# Generated by Django 4.2.7 on 2023-11-13 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('dtInclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=60, unique=True, verbose_name='Descrição')),
                ('dtInclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
            ],
            options={
                'verbose_name': 'Tipo de Formação',
                'verbose_name_plural': 'Tipos de Formação',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Linha_Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120, unique=True)),
                ('dtInclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cursos.curso')),
            ],
            options={
                'ordering': ['curso__nome', 'descricao'],
            },
        ),
    ]
