# Generated by Django 4.2.7 on 2023-11-16 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='tipoFormacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cursos.tipo_formacao'),
            preserve_default=False,
        ),
    ]
