# Generated by Django 5.0.3 on 2024-03-26 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_curso_tipoformacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['tipoFormacao', 'nome']},
        ),
        migrations.AlterModelOptions(
            name='linha_pesquisa',
            options={'ordering': ['curso__nome', 'descricao'], 'verbose_name': 'Linha de Pesquisa', 'verbose_name_plural': 'Linhas de Pesquisas'},
        ),
    ]
