# Generated by Django 4.2.7 on 2023-11-13 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import usuarios.functions_cpf_cnpj


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('cidade_exterior', models.CharField(blank=True, max_length=120, null=True)),
                ('estado_exterior', models.CharField(blank=True, max_length=120, null=True)),
                ('dtInclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.cidade')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('sigla', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Rede_Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Redes Sociais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario_Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_outro', models.CharField(blank=True, max_length=120, null=True)),
                ('dtInicio', models.DateField(verbose_name='Data Contratação')),
                ('dtFim', models.DateField(blank=True, null=True, verbose_name='Data Desligamento')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cargo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário/Empresa',
                'verbose_name_plural': 'Usuários/Empresas',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Usuario_Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtinicio', models.DateField(verbose_name='Data início')),
                ('dtConclusao', models.DateField(verbose_name='Data Conclusão')),
                ('dtInclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cursos.curso')),
                ('linhaPesquisa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cursos.linha_pesquisa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['curso', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[usuarios.functions_cpf_cnpj.validate_CPF])),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro'), ('N', 'Prefiro não dizer')], max_length=1)),
                ('dtNascimento', models.DateField(verbose_name='Data Nascimento')),
                ('celular', models.CharField(max_length=11)),
                ('rua', models.CharField(max_length=120)),
                ('numero', models.CharField(max_length=50, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=120, null=True)),
                ('cidade_exterior', models.CharField(blank=True, max_length=120, null=True)),
                ('estado_exterior', models.CharField(blank=True, max_length=120, null=True)),
                ('cep', models.CharField(max_length=8)),
                ('ativo', models.BooleanField(default=True)),
                ('dtInclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.cidade')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.pais')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('uf', models.CharField(max_length=2, unique=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.pais')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.pais'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.estado'),
        ),
        migrations.AlterUniqueTogether(
            name='cidade',
            unique_together={('estado', 'nome')},
        ),
    ]
