# Generated by Django 5.0.3 on 2024-03-26 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_curso',
            name='tituloDisertacao',
            field=models.CharField(default=1, max_length=200, verbose_name='Título da Dissertação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.pais'),
            preserve_default=False,
        ),
    ]
