# Generated by Django 5.0.3 on 2024-03-26 14:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_curso_titulodisertacao_alter_usuario_pais'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_empresa',
            name='dtInclusao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Dt. Inclusão'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Usuario_RedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=120)),
                ('dtInclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('rede_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.rede_social')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário/Rede Social',
                'verbose_name_plural': 'Usuários/Redes Sociais',
                'ordering': ['user', 'rede_social'],
            },
        ),
    ]
