# Generated by Django 5.0.3 on 2024-03-26 14:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_empresa_dtinclusao_usuario_redesocial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario_redesocial',
            name='link',
        ),
        migrations.AddField(
            model_name='usuario_redesocial',
            name='endereco',
            field=models.CharField(default=django.utils.timezone.now, max_length=120, verbose_name='Endereço'),
            preserve_default=False,
        ),
    ]
