# Generated by Django 5.0.3 on 2024-04-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_usuario_redesocial_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='autorizoExporContato',
            field=models.BooleanField(default=True, verbose_name='Autorizo expor meus dados de contato para integrantes desta plataforma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='autorizoExporCurriculo',
            field=models.BooleanField(default=False, verbose_name='Autorizo expor meus dados sobre formação acadêmica e profissional para integrantes desta plataforma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
