# Generated by Django 5.0.3 on 2024-04-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_tipo_informe_informe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='texto',
            field=models.CharField(max_length=3000),
        ),
    ]
