# Generated by Django 5.0.4 on 2024-04-17 21:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_informe_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='dtExpiracao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Dt. Expiração'),
            preserve_default=False,
        ),
    ]
